### ISSUE TITLE
What else do I need to run this

### ISSUE THREAD

**Issue by roastduck** [elenno/simtest#1]
There is no problems now. It was my fault.

**Comment by elenno** [comment]
Just simply double click the "simtest.jar" to run the simtest (make sure
the simtest.jar is in the same directory with lib) . The project aims at
the usage of ast and how to make simtest more accurate. Please let me know
your idea and feeling about "simtest" , that would be very grateful.
   You are more than welcome to contact me by this email address if you
have more problems. I will do my best to solve it. :)

**Comment by roastduck** [comment]
Well, contact you at this email? But what is the address of this email... What's more, I want a command-line interface so I can use it on my project, an online judge system.

**Comment by elenno** [comment]
You can contact me with this email: elenno.chen@gmail.com  ...

   I don't have an command-line interface. But there is a simple way to do
it like that.  Look at the codes in Main.java, there are some comment
lines. That part of the code is the demo to show how to run the sim test.
Later I will upload a usage file to the show how to use it.

   Are you a Chinese? If you are, we can share ideas in Chinese next time
:)  .
